# Generated by Django 4.2.5 on 2023-11-28 02:21

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
