# Generated by Django 4.2.5 on 2025-03-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_ombi_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discord_id',
        ),
    ]
