# Generated by Django 4.2.5 on 2026-01-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_user_discord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ombi_uid",
            field=models.CharField(
                blank=True, default="", help_text="The Ombi user ID for this user", max_length=255
            ),
        ),
    ]
